development:
  adapter: mysql2
  encoding: utf8
  database: ficoach
  host: localhost
  username: root
  password: 123456

test:
  adapter: mysql2
  encoding: utf8
  database: ficoach
  host: localhost
  username: root
  password: 123456

production:
  adapter: mysql2
  encoding: utf8
  database: ficoach
  host: localhost
  username: root
  password: 123456
