development:
  adapter: mysql2
  encoding: utf8
  database: ficoach_development
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: ficoach_test
  host: localhost
  username: root
  password:
