development:
  adapter: mysql2
  encoding: utf8
  database: ficoach-development
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: ficoach-test
  host: localhost
  username: root
  password:
